# Generated by Django 4.1.4 on 2022-12-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_custo', models.CharField(max_length=40)),
                ('detalhes', models.CharField(max_length=200)),
                ('custo', models.FloatField()),
                ('prazo', models.DateField()),
                ('pago', models.BooleanField(default=True)),
            ],
        ),
    ]
