# Generated by Django 4.1.7 on 2023-03-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ganho', models.CharField(max_length=40)),
                ('valor_ganho', models.FloatField()),
                ('gerado', models.DateTimeField(auto_now_add=True)),
                ('pago', models.BooleanField(default=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advogado.advogado')),
            ],
        ),
        migrations.CreateModel(
            name='Custos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_custo', models.CharField(max_length=40)),
                ('valor_custo', models.FloatField()),
                ('gerado', models.DateTimeField(auto_now_add=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advogado.advogado')),
            ],
            options={
                'verbose_name_plural': 'Custos',
            },
        ),
    ]
