# Generated by Django 4.1.4 on 2023-02-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0004_advogado_usuario'),
        ('escritorio', '0002_alter_custos_options_alter_custos_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custos',
            old_name='custo',
            new_name='valor_custo',
        ),
        migrations.RemoveField(
            model_name='custos',
            name='detalhes',
        ),
        migrations.RemoveField(
            model_name='custos',
            name='prazo',
        ),
        migrations.AddField(
            model_name='custos',
            name='gerado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='custos',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advogado.advogado'),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ganho', models.CharField(max_length=40)),
                ('valor_ganho', models.FloatField()),
                ('gerado', models.DateTimeField(auto_now_add=True)),
                ('pago', models.BooleanField(default=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advogado.advogado')),
            ],
        ),
    ]
