# Generated by Django 4.1.7 on 2023-06-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='cliente_de',
        ),
    ]
