# Generated by Django 4.1.7 on 2023-04-07 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_cpf_cnpj_alter_parteadv_cpf_cnpj'),
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessosAssuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='processosanexos',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='processos',
            name='assunto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='processosanexos',
            name='nome_do_anexo',
            field=models.CharField(max_length=100),
        ),
    ]
