# Generated by Django 4.1.7 on 2023-05-31 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_rename_register_registrycontact_registry'),
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicated_by', to='registry.registry'),
        ),
    ]
