# Generated by Django 4.1.7 on 2023-06-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='assunto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
