# Generated by Django 4.1.7 on 2023-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_processosanexos_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='processosanexos',
            name='nome_do_anexo',
            field=models.CharField(default='Arquivo Sem Nome', max_length=100),
        ),
    ]
