# Generated by Django 4.1.7 on 2023-04-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_rename_responsavel_processoshonorarios_advogado_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processomovimento',
            name='data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='processos',
            name='codigo_processo',
            field=models.CharField(max_length=25),
        ),
    ]
