# Generated by Django 4.1.7 on 2023-05-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_alter_processos_assunto_alter_processos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='assunto',
            field=models.CharField(blank=True, default='Sem observações', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processos',
            name='observacoes',
            field=models.TextField(),
        ),
    ]
