# Generated by Django 4.1.7 on 2023-04-14 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_alter_processomovimento_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processomovimento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
