# Generated by Django 4.1.7 on 2023-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_alter_processos_assunto_alter_processos_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processos',
            name='iniciado',
            field=models.DateTimeField(),
        ),
    ]
