# Generated by Django 4.1.7 on 2023-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_processomovimento_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='processomovimento',
            name='tipo_movimento',
            field=models.CharField(default='Vazio', max_length=255),
        ),
    ]
