# Generated by Django 4.1.7 on 2023-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_processomovimento_tipo_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='estado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processos',
            name='municipio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processos',
            name='posicao',
            field=models.CharField(choices=[('autor', 'Autor'), ('reu', 'Réu')], max_length=5),
        ),
    ]
