# Generated by Django 4.1.7 on 2023-04-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0006_alter_processos_estado_alter_processos_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoshonorarios',
            name='ganho',
            field=models.BooleanField(default=True),
        ),
    ]
