# Generated by Django 4.1.7 on 2023-04-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0007_processoshonorarios_ganho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessoMovimento',
            new_name='ProcessosMovimento',
        ),
    ]
