# Generated by Django 4.1.7 on 2023-05-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_alter_advogado_oab'),
        ('processo', '0008_rename_processomovimento_processosmovimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='advogado_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advogado_responsavel', to='advogado.advogado'),
        ),
    ]
