# Generated by Django 4.1.7 on 2023-05-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0009_alter_processos_advogado_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='n_vara',
        ),
        migrations.AlterField(
            model_name='processosanexos',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_anexos', to='processo.processos'),
        ),
        migrations.AlterField(
            model_name='processoshonorarios',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_honorarios', to='processo.processos'),
        ),
    ]
