# Generated by Django 4.1.7 on 2023-05-23 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParteAdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpf_cnpj', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], max_length=2)),
                ('imagem', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Parte Adversa',
            },
        ),
        migrations.CreateModel(
            name='ParteAdvEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=255)),
                ('parte_adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_part_adress', to='parte_adversa.parteadv')),
            ],
            options={
                'verbose_name_plural': 'Endereços da Parte Adversa',
            },
        ),
        migrations.CreateModel(
            name='ParteAdvContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('parte_adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_part_contact', to='parte_adversa.parteadv')),
            ],
            options={
                'verbose_name_plural': 'Contatos Parte Adversa',
            },
        ),
    ]
