# Generated by Django 4.1.7 on 2023-06-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0005_alter_advogado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='oab',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
