version: '3.8'

services:
  macedoazevedoapp:
    container_name: macwdo/macedoazevedoapp:latest
    image: macwdo/macedoazevedoapp:latest
    ports:
      - "80:8000"
    stdin_open: true 
    tty: true
    env_file: .env
    volumes:
      - ./code:/home/app
