[tool.ruff]
line-length = 79
exclude = ['./venv']

[tool.isort]
profile = "black"
line_length = 79
extend_skip = ['./**/migrations/**']

[tool.pytest.ini_options]
pythonpath = "./src"

[tool.blue]
extend-exclude = '(./**/migrations/**)'

[tool.taskipy.tasks]
lint = 'ruff ./src/ && blue --check ./src/ --diff'
lint_fix = 'ruff ./src/ --fix && blue --check ./src/ --diff'
checker = 'mypy src/manage.py --strict'
format = 'blue ./src  && isort ./src'
