# Generated by Django 4.1.4 on 2022-12-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilesModel',
            new_name='ArquivoModels',
        ),
    ]
