# Generated by Django 4.1.4 on 2022-12-13 20:43

from django.db import migrations, models
import processo.models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_rename_filesmodel_arquivomodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivomodels',
            name='files',
            field=models.FileField(upload_to=processo.models.create_dir),
        ),
    ]
