# Generated by Django 4.1.7 on 2023-03-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Não informado', max_length=100)),
                ('email', models.CharField(default='Não informado', max_length=100)),
                ('numero', models.CharField(default='Não informado', max_length=20)),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(default='Não informado', max_length=200)),
                ('cpf_cnpj', models.CharField(default='Não informado', max_length=30)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='ParteADV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Não informado', max_length=50)),
                ('email', models.CharField(default='Não informado', max_length=50)),
                ('numero', models.CharField(default='Não informado', max_length=20)),
                ('endereco', models.CharField(default='Não informado', max_length=200)),
                ('cpf_cnpj', models.CharField(default='Não informado', max_length=30)),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Parte ADV',
            },
        ),
        migrations.CreateModel(
            name='ContaParteAdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.CharField(default='Não informado', max_length=150)),
                ('agencia', models.CharField(default='Não informado', max_length=150)),
                ('conta', models.CharField(default='Não informado', max_length=150)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.parteadv')),
            ],
        ),
        migrations.CreateModel(
            name='ContaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.CharField(default='Não informado', max_length=150)),
                ('agencia', models.CharField(default='Não informado', max_length=150)),
                ('conta', models.CharField(default='Não informado', max_length=150)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
