# Generated by Django 4.1.7 on 2023-05-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(default='Vazio', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(default='Vazio', max_length=100),
        ),
    ]
