# Generated by Django 4.1.7 on 2023-03-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(default='Não Identificado', max_length=255)),
                ('complemento', models.CharField(default='Não Identificado', max_length=255)),
                ('cep', models.CharField(default='Não Identificado', max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ParteADVEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(default='Não Identificado', max_length=255)),
                ('complemento', models.CharField(default='Não Identificado', max_length=255)),
                ('cep', models.CharField(default='Não Identificado', max_length=30)),
                ('parte_adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.parteadv')),
            ],
        ),
        migrations.RemoveField(
            model_name='contaparteadv',
            name='registro',
        ),
        migrations.DeleteModel(
            name='ContaCliente',
        ),
        migrations.DeleteModel(
            name='ContaParteAdv',
        ),
    ]
