# Generated by Django 4.1.7 on 2023-04-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parteadv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
