# Generated by Django 4.1.7 on 2023-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='email',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
