# Generated by Django 4.1.7 on 2023-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_clienteendereco_parteadvendereco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='registro',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='parteadv',
            old_name='registro',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='parteadv',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
