# Generated by Django 4.1.7 on 2023-04-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_updated_at_parteadv_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(default='Não Informado'),
        ),
    ]
