# Generated by Django 4.1.7 on 2023-05-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_estado_civil_alter_cliente_profissao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='imagem',
            new_name='image',
        ),
    ]
