# Generated by Django 4.1.7 on 2023-04-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteadv',
            name='endereco',
            field=models.TextField(default='Não Informado'),
        ),
    ]
