# Generated by Django 4.1.7 on 2023-05-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_rename_imagem_cliente_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteendereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_address', to='cliente.cliente'),
        ),
    ]
