# Generated by Django 4.1.4 on 2022-12-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Cliente'},
        ),
        migrations.AlterModelOptions(
            name='clientepf',
            options={'verbose_name_plural': 'Cliente PF'},
        ),
        migrations.AlterModelOptions(
            name='clientepj',
            options={'verbose_name_plural': 'Cliente PJ'},
        ),
        migrations.AlterModelOptions(
            name='parteadv',
            options={'verbose_name_plural': 'Parte ADV'},
        ),
        migrations.AlterModelOptions(
            name='parteadvpf',
            options={'verbose_name_plural': 'Parte ADV PF'},
        ),
        migrations.AlterModelOptions(
            name='parteadvpj',
            options={'verbose_name_plural': 'Parte ADV PJ'},
        ),
    ]
