# Generated by Django 4.1.7 on 2023-03-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_registro_alter_parteadv_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(default='Não informado', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, default='Não informado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='Não informado', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, default='Não informado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='cpf_cnpj',
            field=models.CharField(default='Não informado', max_length=30),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='email',
            field=models.CharField(blank=True, default='Não informado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='nome',
            field=models.CharField(default='Não informado', max_length=50),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='numero',
            field=models.CharField(blank=True, default='Não informado', max_length=20, null=True),
        ),
    ]
