# Generated by Django 4.1.7 on 2023-03-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_cpf_cnpj_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='Não informado', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='Não informado', max_length=20),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='email',
            field=models.CharField(default='Não informado', max_length=50),
        ),
        migrations.AlterField(
            model_name='parteadv',
            name='numero',
            field=models.CharField(default='Não informado', max_length=20),
        ),
    ]
