# Generated by Django 4.1.7 on 2023-03-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_email_alter_cliente_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.CreateModel(
            name='ContaParteAdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.CharField(default='Não informado', max_length=150)),
                ('agencia', models.CharField(default='Não informado', max_length=150)),
                ('conta', models.CharField(default='Não informado', max_length=150)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.parteadv')),
            ],
        ),
        migrations.CreateModel(
            name='ContaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.CharField(default='Não informado', max_length=150)),
                ('agencia', models.CharField(default='Não informado', max_length=150)),
                ('conta', models.CharField(default='Não informado', max_length=150)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
