# Generated by Django 4.1.7 on 2023-03-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
