# Generated by Django 4.1.7 on 2023-03-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteadv',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=200),
        ),
    ]
