# Generated by Django 4.1.7 on 2023-06-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('oab', models.CharField(blank=True, max_length=12, unique=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Advogado',
            },
        ),
    ]
