# Generated by Django 4.1.7 on 2023-05-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('oab', models.CharField(blank=True, max_length=10, unique=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Advogado',
            },
        ),
    ]
