<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-06-03 05:19
=======
# Generated by Django 4.1.7 on 2023-06-06 17:42
>>>>>>> main

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advogado', '0001_initial'),
=======
        ('advogado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> main
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
<<<<<<< HEAD
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
=======
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer_user', to=settings.AUTH_USER_MODEL),
>>>>>>> main
        ),
    ]
