# Generated by Django 4.1.7 on 2023-06-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
