# Generated by Django 4.1.7 on 2023-05-30 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advogado', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
