# Generated by Django 4.1.7 on 2023-06-06 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advogado', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advogado',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='advogado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='advogado',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='oab',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
