# Generated by Django 4.1.7 on 2023-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_alter_advogado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='oab',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
