# Generated by Django 4.1.7 on 2023-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0003_advogado_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
