# Generated by Django 4.1.7 on 2023-04-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0003_alter_advogado_oab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='oab',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
