# Generated by Django 4.1.7 on 2023-06-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0006_alter_advogado_oab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='oab',
            field=models.CharField(max_length=12),
        ),
    ]
