# Generated by Django 4.1.4 on 2022-12-16 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import processo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '__first__'),
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_processo', models.CharField(max_length=25)),
                ('posicao', models.CharField(choices=[('Autor', 'Autor'), ('Réu', 'Réu')], max_length=5)),
                ('assunto', models.CharField(choices=[('Trabalhista', 'Direito Trabalhista'), ('Previdenciário', 'Direito Previdenciário'), ('Civil', 'Direito Civil')], max_length=15)),
                ('observacoes', models.CharField(blank=True, default='Sem observações', max_length=255, null=True)),
                ('honorarios', models.FloatField(blank=True, default=0)),
                ('municipio', models.CharField(max_length=35)),
                ('estado', models.CharField(max_length=2)),
                ('n_vara', models.CharField(max_length=10)),
                ('vara', models.CharField(max_length=50)),
                ('iniciado', models.DateField(default=datetime.date.today)),
                ('finalizado', models.DateTimeField(blank=True, null=True)),
                ('arquivos', models.FileField(blank=True, default='', null=True, upload_to=processo.models.dir_files_processo)),
                ('advogado_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advogado_responsavel', to='advogado.advogado')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cliente.cliente')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to='advogado.advogado')),
                ('parte_adversa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parte_adversa', to='cliente.parteadv')),
            ],
            options={
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='ProcessosArquivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, default='', null=True, upload_to=processo.models.dir_files_processo)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='processo.processos')),
            ],
            options={
                'verbose_name_plural': 'Processos Arquivos',
            },
        ),
    ]
