# Generated by Django 4.1.4 on 2023-02-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_alter_cliente_registro_alter_parteadv_registro'),
        ('advogado', '0004_advogado_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_processo', models.CharField(max_length=25, unique=True)),
                ('posicao', models.CharField(choices=[('Autor', 'Autor'), ('Réu', 'Réu')], max_length=5)),
                ('assunto', models.CharField(choices=[('Trabalhista ', 'Direito Trabalhista'), ('Previdenciário', 'Direito Previdenciário'), ('Civil', 'Direito Civil')], max_length=15)),
                ('observacoes', models.CharField(blank=True, default='Sem observações', max_length=255, null=True)),
                ('honorarios', models.FloatField(blank=True, default=0)),
                ('municipio', models.CharField(max_length=35)),
                ('estado', models.CharField(max_length=2)),
                ('n_vara', models.CharField(max_length=10)),
                ('vara', models.CharField(max_length=50)),
                ('iniciado', models.DateTimeField(auto_now=True)),
                ('finalizado', models.DateTimeField(blank=True, null=True)),
                ('anexo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('advogado_responsavel', models.ForeignKey(default='Não Informado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advogado_responsavel', to='advogado.advogado')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cliente.cliente')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to='advogado.advogado')),
                ('parte_adversa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.parteadv')),
            ],
            options={
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
