# Generated by Django 4.1.4 on 2022-12-15 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import processo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '__first__'),
        ('advogado', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_processo', models.CharField(max_length=25)),
                ('posicao', models.CharField(choices=[('Autor', 'Autor'), ('Réu', 'Réu')], max_length=5)),
                ('assunto', models.CharField(choices=[('Trabalhista', 'Direito Trabalhista'), ('Previdenciário', 'Direito Previdenciário'), ('Civil', 'Direito Civil')], max_length=15)),
                ('observacoes', models.CharField(blank=True, default='Sem observações', max_length=255, null=True)),
                ('honorarios', models.FloatField(blank=True, default=0)),
                ('municipio', models.CharField(max_length=35)),
                ('estado', models.CharField(max_length=2)),
                ('n_vara', models.CharField(max_length=10)),
                ('vara', models.CharField(max_length=50)),
                ('iniciado', models.DateField(default=django.utils.timezone.now)),
                ('finalizado', models.DateTimeField(blank=True, null=True)),
                ('advogado_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advogado_responsavel', to='advogado.Advogado')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessosArquivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivos', models.FileField(upload_to=processo.models.dir_files_processo)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.processos')),
            ],
        ),
        migrations.AddField(
            model_name='processos',
            name='arquivos',
            field=models.ManyToManyField(blank=True, to='processo.processosarquivos'),
        ),
        migrations.AddField(
            model_name='processos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='processos',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to='advogado.Advogado'),
        ),
        migrations.AddField(
            model_name='processos',
            name='parte_adversa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parte_adversa', to='cliente.parteadv'),
        ),
    ]
