# Generated by Django 4.1.4 on 2023-02-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='assunto',
            field=models.CharField(choices=[('Trabalhista', 'Direito Trabalhista'), ('Previdenciário', 'Direito Previdenciário'), ('Civil', 'Direito Civil')], max_length=15),
        ),
    ]
