# Generated by Django 4.1.4 on 2022-12-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0001_initial'),
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='advogado_responsavel',
            field=models.ForeignKey(default='Não Informado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advogado_responsavel', to='advogado.advogado'),
        ),
    ]
