# Generated by Django 4.1.4 on 2022-12-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processos',
            options={'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterModelOptions(
            name='processosarquivos',
            options={'verbose_name_plural': 'Processos Arquivos'},
        ),
    ]
