# Generated by Django 4.1.4 on 2022-12-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='codigo_processo',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='processosarquivos',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='processo.processos'),
        ),
    ]
