# Generated by Django 4.1.7 on 2023-03-05 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0004_advogado_usuario'),
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='cliente_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advogado.advogado'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='assunto',
            field=models.CharField(choices=[('Trabalhista', 'Direito Trabalhista'), ('Previdenciário', 'Direito Previdenciário'), ('Civil', 'Direito Civil')], max_length=15),
        ),
        migrations.AlterField(
            model_name='processos',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='processos',
            name='iniciado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processos',
            name='municipio',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='processos',
            name='n_vara',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='ProcessoHonorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referente', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.processos')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advogado.advogado')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoAnexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.processos')),
            ],
        ),
        migrations.AlterField(
            model_name='processos',
            name='anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processo.processoanexos'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='honorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processo.processohonorarios'),
        ),
    ]
