# Generated by Django 4.1.4 on 2023-02-13 10:37

from django.db import migrations, models
import django.db.models.deletion
import processo.models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_registro_alter_parteadv_registro'),
        ('processo', '0002_alter_processos_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='cliente_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='anexo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=processo.models.dir_files_processo),
        ),
        migrations.AlterField(
            model_name='processos',
            name='iniciado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
