# Generated by Django 4.1.7 on 2023-03-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_processos_cliente_de_alter_processos_assunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='honorarios',
        ),
        migrations.AddField(
            model_name='processos',
            name='honorarios',
            field=models.ManyToManyField(to='processo.processohonorarios'),
        ),
    ]
