# Generated by Django 4.1.4 on 2022-12-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_alter_processos_advogado_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='posicao',
            field=models.BooleanField(default=False),
        ),
    ]
