# Generated by Django 4.1.7 on 2023-03-06 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_remove_processos_honorarios_processos_honorarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='honorarios',
        ),
        migrations.AddField(
            model_name='processos',
            name='honorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processo.processohonorarios'),
        ),
    ]
