# Generated by Django 4.1.4 on 2022-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_alter_processos_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='posicao',
            field=models.CharField(choices=[('Autor', 'Autor'), ('Réu', 'Réu')], max_length=5),
        ),
    ]
