# Generated by Django 4.1.4 on 2023-02-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0004_advogado_usuario'),
        ('processo', '0003_processos_cliente_de_alter_processos_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='cliente_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advogado.advogado'),
        ),
    ]
