# Generated by Django 4.1.4 on 2023-01-19 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_alter_processos_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='iniciado',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
