# Generated by Django 4.1.7 on 2023-03-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_remove_processos_honorarios_processos_honorarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='honorarios',
        ),
    ]
