# Generated by Django 4.1.4 on 2023-02-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_alter_processos_cliente_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='processos',
            name='municipio',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='processos',
            name='n_vara',
            field=models.CharField(max_length=30),
        ),
    ]
