# Generated by Django 4.1.7 on 2023-03-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_remove_processos_anexo_remove_processos_honorarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoanexos',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='processo.processos'),
        ),
        migrations.AlterField(
            model_name='processohonorarios',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorarios', to='processo.processos'),
        ),
    ]
