version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando o processo de build..."
      - echo "Fazendo o login no ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${URL}

  build:
    commands:
      - echo "Construindo a imagem do Docker..."
      - docker build -t magunicorn:latest .
      - docker tag magunicorn:latest ${URL}/magunicorn:latest

  post_build:
    commands:
      - echo "Empurrando a imagem para o ECR..."
      - docker push ${URL}/magunicorn:latest