# Generated by Django 4.1.4 on 2022-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('honorarios', models.FloatField(blank=True, default=0)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
