# Generated by Django 4.1.4 on 2022-12-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='image',
            field=models.ImageField(default='None', upload_to=''),
        ),
    ]
