# Generated by Django 4.1.4 on 2022-12-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advogado',
            options={'verbose_name_plural': 'Advogado'},
        ),
    ]
