# Generated by Django 4.1.4 on 2023-01-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_advogado_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advogado',
            name='image',
        ),
    ]
