# Generated by Django 4.1.7 on 2023-05-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_registrycnpj_registry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrycontact',
            old_name='register',
            new_name='registry',
        ),
    ]
