# Generated by Django 4.1.7 on 2023-06-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_registrycnpj_registry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrycnpj',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registry_cnpj', serialize=False, to='registry.registry'),
        ),
        migrations.AlterField(
            model_name='registrycpf',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registry_cpf', serialize=False, to='registry.registry'),
        ),
    ]
