# Generated by Django 4.1.7 on 2023-06-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_registry_civil_state_alter_registry_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='civil_state',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='profession',
        ),
        migrations.AddField(
            model_name='registrycnpj',
            name='interprise_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrycpf',
            name='civil_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrycpf',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registryaddress',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
