name: Django CD

on:
  push:
    branches: [ "feature/cicd" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to prod"

    steps:
      - name: Checkout Files
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END


      - name: Copying .env file for ec2
        run: |
          echo "$ENV_VARIABLES" > .env

      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: ".env"
          target: "~/"
  

      - name: Down app and cleaning
        run: ssh prod 'if [ -n "$(docker ps -q)" ]; then docker kill $(docker ps -q); system prune --force'

      - name: Pulling image from Dockerhub
        run: ssh prod "docker pull macwdo/macedoazevedoapp:latest"

      - name: Up app
        run: ssh prod "docker run --env-file ./.env -p 80:8000 -d macwdo/macedoazevedoapp:latest"

        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          ENV_VARIABLES: ${{ secrets.ENV_VARIABLES }}