name: Django CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dotenv Action
        uses: falti/dotenv-action@v1.0.1
        with:
          path: .envexample

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/requirements.txt

      - name: Run Tests
        run: |
          cd code; python manage.py test


  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: "Deploy to prod"

    steps:
      - name: Checkout Files
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}


      - name: Pulling github code
        run: ssh prod "git pull"

      - name: Restarting service
        run: ssh prod "systemctl restart nginx | systemctl restart gunicorn"